### ISSUE TITLE
Big checklist

### ISSUE THREAD

**Issue by leeyap** [JGCRI/trackingC#40]
**Code tasks**

- [ ]  AF trend #37 
- [x] Turn on tracking in 1750
- [x] Finish up #38 and adjust necessary figures
~- [ ] A fresh attempt at parallelization~ _tabling for now_

----

**Writing tasks**

- [x]  Add to methods section: variance decomposition, classic AF vs source/destination AF, closing paragraph on code and data availability
- [x] Make tweaks from comments
- [x] Clean up Rmd document - add in proper figure numbers, remove warning messages
- [x] Clean up introduction

----

**Presentation tasks**

_For GCAM annual meeting_
- [x] Freeze point: Once #38 is complete
- [x] Draft poster due May 20 in IR, final poster due May 27
- [x] Get sample poster to work off of
- [x] Short speech

~_For LTE monthly meeting_~ _moved to October_
~- [ ]  Take poster content and translate to a short talk~

_For coauthor meeting_
Week of 6/13 or 6/27
- [ ] Have storyline crafted, code and writing tasks above completed
